import {
  AlertCircle,
  AlertTriangle,
  ArrowDownAZ,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  AtSign,
  Backpack,
  BadgeCheck,
  Ban,
  BookOpen,
  Box,
  Boxes,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDot,
  CircleUser,
  Clock,
  Cloud,
  Compass,
  Coins,
  Copy,
  Database,
  Dices,
  Download,
  Dumbbell,
  Eraser,
  ExternalLink,
  FileText,
  Film,
  Flame,
  FolderOpen,
  FolderTree,
  Frown,
  Gift,
  HardDrive,
  Heart,
  Home,
  Hourglass,
  Image,
  ImageOff,
  Images,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  List,
  ListChecks,
  ListFilter,
  Lock,
  LockOpen,
  LogIn,
  Map,
  MapPin,
  Medal,
  Cpu,
  Menu,
  MessageSquare,
  Minimize2,
  Maximize2,
  Pause,
  PictureInPicture2,
  Rewind,
  FastForward,
  SkipBack,
  SkipForward,
  Gauge,
  Captions,
  VolumeX,
  Minus,
  Moon,
  MoreVertical,
  MousePointer2,
  Move,
  Newspaper,
  PanelLeft,
  PartyPopper,
  PawPrint,
  Pencil,
  Pin,
  Play,
  PlayCircle,
  Plus,
  Puzzle,
  RefreshCw,
  Repeat,
  RotateCcw,
  Rows3,
  Rss,
  Save,
  Scaling,
  ScanSearch,
  Search,
  SearchX,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Store,
  Sun,
  Swords,
  Table,
  Tag,
  Timer,
  Trash2,
  TrendingUp,
  Undo2,
  Upload,
  User,
  UserPlus,
  UserSearch,
  Users,
  Volume2,
  WandSparkles,
  Wifi,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * Mapping noms « Material Symbols » -> icônes lucide-react.
 * Même vocabulaire de noms que `apps/azalee/lib/icons.ts` (identité visuelle
 * commune) + quelques ajouts propres à niers (extension Blender, aperçu vidéo/
 * audio/3D, mods). Aucune police d'icônes réseau : tout est du SVG lucide déjà
 * embarqué dans le bundle — compatible offline.
 */
export const iconMap: Record<string, LucideIcon> = {
  account_circle: CircleUser,
  account_tree: FolderTree,
  add: Plus,
  alternate_email: AtSign,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  article: FileText,
  auto_awesome: Sparkles,
  backpack: Backpack,
  block: Ban,
  blur_on: CircleDot,
  bolt: Zap,
  broken_image: ImageOff,
  build: Wrench,
  calendar_today: Calendar,
  casino: Dices,
  change_circle: RefreshCw,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud: Cloud,
  compare_arrows: ArrowLeftRight,
  construction: Wrench,
  content_copy: Copy,
  crop_square: Square,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  database: Database,
  deployed_code: Boxes,
  delete: Trash2,
  delete_sweep: Eraser,
  description: FileText,
  download: Download,
  edit: Pencil,
  edit_note: FileText,
  error: AlertCircle,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  explore: Compass,
  extension: Puzzle,
  favorite: Heart,
  feed: Rss,
  filter_list: ListFilter,
  fitness_center: Dumbbell,
  flash_on: Zap,
  folder: FolderOpen,
  folder_open: FolderOpen,
  forum: MessageSquare,
  fullscreen: Maximize2,
  fullscreen_exit: Minimize2,
  pause: Pause,
  picture_in_picture: PictureInPicture2,
  fast_rewind: Rewind,
  fast_forward: FastForward,
  skip_previous: SkipBack,
  skip_next: SkipForward,
  speed: Gauge,
  closed_caption: Captions,
  volume_off: VolumeX,
  gavel: Shield,
  grid_view: LayoutGrid,
  group: Users,
  group_add: UserPlus,
  groups: Users,
  hard_drive: HardDrive,
  home: Home,
  hourglass_top: Hourglass,
  image: Image,
  image_search: ScanSearch,
  light_mode: Sun,
  lightbulb: Lightbulb,
  link: ExternalLink,
  local_fire_department: Flame,
  lock: Lock,
  lock_open: LockOpen,
  login: LogIn,
  memory: Cpu,
  menu: Menu,
  menu_book: BookOpen,
  monitoring: TrendingUp,
  more_vert: MoreVertical,
  movie: Film,
  music_note: Volume2,
  near_me: MousePointer2,
  newspaper: Newspaper,
  open_in_new: ExternalLink,
  open_with: Move,
  panel_left: PanelLeft,
  payments: Coins,
  perm_media: Images,
  person: User,
  person_celebrate: PartyPopper,
  person_search: UserSearch,
  pets: PawPrint,
  pin_drop: MapPin,
  play_arrow: Play,
  play_circle: PlayCircle,
  policy: ShieldCheck,
  push_pin: Pin,
  radio_button_unchecked: Circle,
  redeem: Gift,
  remove: Minus,
  replay: Repeat,
  rotate_ccw: RotateCcw,
  save: Save,
  scale: Scaling,
  schedule: Clock,
  search: Search,
  search_off: SearchX,
  sentiment_dissatisfied: Frown,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shield_person: ShieldCheck,
  shopping_bag: ShoppingBag,
  sort_by_alpha: ArrowDownAZ,
  sports: Medal,
  sports_martial_arts: Swords,
  sports_soccer: CircleDot,
  stadium: CircleDot,
  stars: Star,
  store: Store,
  storefront: Store,
  strategy: Map,
  swap_horiz: ArrowLeftRight,
  swords: Swords,
  table_chart: Table,
  table_rows: Rows3,
  tag: Tag,
  task_alt: ListChecks,
  timer: Timer,
  translate: Languages,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  undo: Undo2,
  update: RefreshCw,
  upload: Upload,
  verified: BadgeCheck,
  view_in_ar: Box,
  view_list: List,
  volume_up: Volume2,
  wand: WandSparkles,
  warning: AlertTriangle,
  wifi_tethering: Wifi,
};

export interface IconProps {
  name: keyof typeof iconMap | (string & {});
  size?: number;
  className?: string;
  fill?: boolean;
}

/** Icône par nom « Material Symbols », rendue en SVG lucide-react (offline). */
export function Icon({ name, size = 20, className, fill = false }: IconProps) {
  const LucideIconCmp = iconMap[name as string];
  if (!LucideIconCmp) return null;
  return (
    <LucideIconCmp
      size={size}
      className={cn(className)}
      fill={fill ? "currentColor" : "none"}
      aria-hidden="true"
    />
  );
}
